module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine'],
    files: [
      'node_modules/angular/angular.min.js',
      'node_modules/angular-route/angular-route.min.js',
      'node_modules/angular-mocks/angular-mocks.js',
      'app.js',
      'services/auth.service.js',
      'services/api.service.js',
      'services/profile.service.js',
      'services/vehicle.service.js',
      'services/driver.service.js',
      'services/quote.service.js',
      'services/policy.service.js',
      'services/claim.service.js',
      'services/payment.service.js',
      'controllers/login.controller.js',
      'controllers/register.controller.js',
      'controllers/dashboard.controller.js',
      'controllers/profile.controller.js',
      'controllers/vehicles.controller.js',
      'controllers/drivers.controller.js',
      'controllers/quote.controller.js',
      'controllers/quotes.controller.js',
      'controllers/quote-detail.controller.js',
      'controllers/policies.controller.js',
      'controllers/policy-detail.controller.js',
      'controllers/claims.controller.js',
      'controllers/claim-new.controller.js',
      'controllers/claim-detail.controller.js',
      'controllers/payments.controller.js',
      'tests/**/*.spec.js'
    ],
    exclude: [],
    preprocessors: {},
    reporters: ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: ['ChromeHeadless'],
    singleRun: true,
    concurrency: Infinity
  });
};
